title:            Just Share Blog
description:      A blog about blogging, social media marketing, life, technology, gadgets, ideas, startups, music, and much more.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://justshare.github.io
#url:              http://localhost:4000
disqus_shortname: justshareapp
mixpanel_code:    cf47f8688b7b7b06cdc64e0bf1a87446

# Owner/author information
owner:
  name:           Just Share
  avatar:         bio-jus.jpg
  bio:            "A blog about blogging, social media marketing, life, technology, gadgets, ideas, startups, music, and much more."
  email:          your@email.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        justshareapp
  facebook:
  github:
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Author(s) information
authors:
  arvi:
    name:           Arvi Krishnaswamy
    avatar:         bio-arvi.jpg
    bio:            "Entrepreneur and Tech Executive."
    email:          arvi@alumni.iastate.edu
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    twitter:        twitortat
    facebook:       aravind.krishnaswamy
    github:          arg0s
    stackoverflow:
    linkedin:        aravindkrishnaswamy
    instagram:
    lastfm:
    tumblr:
    pinterest:
    foursquare:
    steam:
    dribbble:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:
  lavanya:
    name:           Lavanya Gopinath
    avatar:         https://pbs.twimg.com/profile_images/418789915166380032/nn5afiTl.jpeg
    bio:            "Reader, Writer, Nitpicker, Mom."
    email:          your@email.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    twitter:        justjots
    facebook:
    github:
    stackoverflow:
    linkedin:
    instagram:
    lastfm:
    tumblr:
    pinterest:
    foursquare:
    steam:
    dribbble:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:
  vinu:
    name:           Vinu Thomas
    avatar:         https://pbs.twimg.com/profile_images/2721037855/c64935721ff73df716b75498baa50dd1.jpeg
    bio:            "Architect on Scalable Web Solutions, and opensource technologies, part-time mobile blogger."
    email:          your@email.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    twitter:        vinuthomas
    facebook:
    github:
    stackoverflow:
    linkedin:
    instagram:
    lastfm:
    tumblr:
    pinterest:
    foursquare:
    steam:
    dribbble:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:
  raj:
    name:           Raj Kannan
    avatar:         http://graph.facebook.com/rajaram.kannan.3/picture?height=150&width=150
    bio:            "Raj is a senior tech executive and an eternal hobbyist. He loves to create products that bring real world experiences to your mobile phones."
    email:          rajaram_kannan@yahoo.com
    # Social networking links are used in author-bio sidebar. Update and remove as you like.
    twitter:        rajaram_kannan
    facebook:
    github:
    stackoverflow:
    linkedin:
    instagram:
    lastfm:
    tumblr:
    pinterest:
    foursquare:
    steam:
    dribbble:
    # For Google Authorship https://plus.google.com/authorship
    google_plus:


# Analytics and webmaster tools stuff goes here
google_analytics: UA-35664860-6
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about/
  - title: Posts
    url: /posts/
  - title: About Levitum
    url: http://www.levitum.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkota
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
